site_name: '雪浪算盘帮助文档中心'
site_author: xuelang-help-center
site_description: '雪浪算盘帮助文档中心'
#site_url: https://spnext.xuelangyun.com/docs/
# site_dir: ../dist/help-center

# File Directory

dev_addr: 0.0.0.0:8082
theme:
  name: material
  language: 'zh'
  favicon: 'assets/favicon.png'
  font: false
  feature:
    tabs: false
extra_javascript:
  - 'assets/js/jquery-3.2.1.min.js'
  - 'assets/js/simpleLightbox.min.js'
  - 'assets/js/custom.js'
#extra:
#  search:
#    language: 'ja'
markdown_extensions:
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - abbr
  - tables
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
